import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/Provider";
import "leaflet/dist/leaflet.css";
// import icon from 'leaflet/dist/images/marker-icon.png';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lead Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </Providers>
  );
}
